<?php

namespace IPNJ\AdminBundle\Repository;

/**
 * EnviosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnviosRepository extends \Doctrine\ORM\EntityRepository
{
}
