<?php

namespace IPNJ\AdminBundle\Repository;

/**
 * IglesiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IglesiasRepository extends \Doctrine\ORM\EntityRepository
{
}
