<?php

namespace IPNJ\AdminBundle\Repository;

/**
 * ZonasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonasRepository extends \Doctrine\ORM\EntityRepository
{
}
