# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    #Envios:
    #    class: IPNJ\AdimBundle\Form\EnviosType
    #    public: true
    #    arguments:  ['@security.token_storage']

    #Asistencia:
    #    class: IPNJ\AdimBundle\Form\AsistenciaType
    #    public: true
    #    arguments:  ['@security.token_storage']